### ISSUE TITLE
install getfilename2

### ISSUE THREAD

**Issue by jgoebel** [ddionrails/soeptools#1]
ssc install getfilename2 
did not find getfilename2 after installation of soeptools using net from(...)

Restarting stata and ssc install works.

**Comment by kwenzig** [comment]
Was there no warning like this one?
![warning](https://cloud.githubusercontent.com/assets/6614820/14491148/79114c5a-0177-11e6-9f77-b740e0d86532.PNG)

**Comment by jgoebel** [comment]
Works with stata 13
