### ISSUE TITLE
version restriction

### ISSUE THREAD

**Issue by jgoebel** [ddionrails/soeptools#2]
can we set 

``` stata
program define soepusemerge , nclass
    version 13
```

to 

``` stata
program define soepusemerge , nclass
    version 12
```

**Comment by jgoebel** [comment]
Under Linux with Stata 12 the following line does not work with our path definitions (with something like "~/tmp/" it does work):

``` stata
local mergefiles : dir "`using'" files "`fileroot'_*.dta"
```

In stata 13 is does work also with our path definitions. 

Strange?

**Comment by kwenzig** [comment]
Please give example for not working path definition, I'll check that using Stata12-32 (windows) and then try to change version line.

**Comment by jgoebel** [comment]
We should stick to version 13
