### ISSUE TITLE
Warnings should be more explicit

### ISSUE THREAD

**Issue by jgoebel** [ddionrails/soeptools#3]
Messages like 

``` stata
    if "`file`fileno'_usevars'"=="" | "`file`fileno'_status'"=="NO, rows do not match" {
        display "Not merged."
    }
```

can be ignored easily.

Do stata have some "warning" messages? Or just using something like

``` stata
        display "======= WARNING ======="
        display "Not merged."
        display "======================="
```

**Comment by kwenzig** [comment]
I updated the results a little bit:
![result](https://cloud.githubusercontent.com/assets/6614820/14494304/844dcc3e-018a-11e6-856b-4d4fc3e28cde.PNG)
If you think, that a special warning must not be ignored, I would recommend an option (something like force), were the default is, that the issue produces an error.

**Comment by kwenzig** [comment]
There are now Excel-Sheets, with many log informations.
