### ISSUE TITLE
Using rsync instead of copy

### ISSUE THREAD

**Issue by jgoebel** [ddionrails/soeptools#4]
Seems to work now, at least after one rsync run:

``` bash
jgoebel@******:/mnt/rdc-gen> rsync -av  consolidated/soep-core/soep.v32/*.dta generations/soep-core/soep.v32/pre/
sending incremental file list

sent 9,651 bytes  received 12 bytes  19,326.00 bytes/sec
total size is 2,500,156,846  speedup is 258,735.06
```

https://github.com/ddionrails/soeptools/blob/master/soepgenpre/soepgenpre.ado#L152

should use something like (when using options rsync)

``` stata
 shell  rsync -a "`consolidated'`file'.dta" "`pre'`file'.dta"
```

**Comment by kwenzig** [comment]
Should rsync be used to copy from consolidated or also from complete? (rsync will not be possible for partial)

**Comment by jgoebel** [comment]
Good point, yes for both (consolidated and complete).

**Comment by kwenzig** [comment]
Please update ado with

```
. adoupdate soeptools, update
```

and test new option `rsync`.

**Comment by jgoebel** [comment]
Works fine. Only a lot of blank lines as output, see
See https://github.com/ddionrails/soeptools/pull/5
